global:
  scrape_interval:     10s 
  evaluation_interval: 10s 

scrape_configs:
  - job_name: 'gnmic'
    scrape_interval: 10s 
    consul_sd_configs:
      - server: clab-sonic-consul-agent:8500
        services:
          - prometheus-prom-output
