{
 "title": "Nokia SRLinux",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "label": "Node", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  { "title": "Stats for $Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_average_1{source=\"$Node\"}",
     "legendFormat": "CPU 1 Sec"
    },
    {
     "expr": "platform_control_cpu_total_average_5{source=\"$Node\"}",
     "legendFormat": "CPU 5 Sec"
    },
    {
     "expr": "platform_control_cpu_total_average_15{source=\"$Node\"}",
     "legendFormat": "CPU 15 Sec"
    }
   ]
  },
  {
   "title": "Memory Physical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_memory_physical{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_memory_free{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Physical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "platform_control_memory_reserved{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "platform_control_memory_utilization{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Oper Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_oper_state{source=\"$Node\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress and Egress Octets",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 15, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_statistics_in_octets{source=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "interface_statistics_out_octets{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running SR Linux applications",
   "type": "table",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "system_app_management_application_pid{source='$Node'}",
     "legendFormat": "{{application_name}}"
    }
   ]
  }
 ]
}