{
 "title": "SONiC Traffic Status",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Arista", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingress Throughput- Ethernet33",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(COUNTERS_Ethernet33_SAI_PORT_STAT_IF_IN_OCTETS[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Throughput- Ethernet36",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(COUNTERS_Ethernet33_SAI_PORT_STAT_IF_OUT_OCTETS[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Pkts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "COUNTERS_Ethernet36_SAI_PORT_STAT_IF_IN_UCAST_PKTS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frame Size",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COUNTERS_Ethernet33_SAI_PORT_STAT_ETHER_IN_PKTS_1024_TO_1518_OCTETS",
     "legendFormat": "1024-1518"
    },
    {
     "expr": "COUNTERS_Ethernet33_SAI_PORT_STAT_ETHER_IN_PKTS_128_TO_255_OCTETS",
     "legendFormat": "128-255"
    },
    {
     "expr": "COUNTERS_Ethernet33_SAI_PORT_STAT_ETHER_IN_PKTS_256_TO_511_OCTETS",
     "legendFormat": "256-511"
    },
    {
     "expr": "COUNTERS_Ethernet33_SAI_PORT_STAT_ETHER_IN_PKTS_4096_TO_9216_OCTETS",
     "legendFormat": "4096-9216"
    },
    {
     "expr": "COUNTERS_Ethernet33_SAI_PORT_STAT_ETHER_IN_PKTS_512_TO_1023_OCTETS",
     "legendFormat": "512-1023"
    },
    {
     "expr": "COUNTERS_Ethernet33_SAI_PORT_STAT_ETHER_IN_PKTS_65_TO_127_OCTETS",
     "legendFormat": "65-127"
    }
   ]
  },
  {
   "title": "Ingress Pkts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "COUNTERS_Ethernet36_SAI_PORT_STAT_IF_OUT_UCAST_PKTS",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nokia SR-7-7750", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Ingress Throughput- Ethernet36",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(COUNTERS_Ethernet36_SAI_PORT_STAT_IF_IN_OCTETS[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Throughput- Ethernet36",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(COUNTERS_Ethernet36_SAI_PORT_STAT_IF_OUT_OCTETS[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unicast Ingress Pkts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "COUNTERS_Ethernet36_SAI_PORT_STAT_IF_IN_UCAST_PKTS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unicast Ingress Pkts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "COUNTERS_Ethernet36_SAI_PORT_STAT_IF_OUT_UCAST_PKTS",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}